/**
 * Temporary type definitions for Sanity query results
 * These should be generated by running `pnpm run typegen`
 * For now, we define them manually based on the query structures
 */

// Booking query results
export type HOST_BOOKINGS_BY_CLERK_ID_QUERYResult = Array<{
  _id: string
  _type: "booking"
  guestName?: string
  guestEmail?: string
  startTime?: string
  endTime?: string
  notes?: string
  googleEventId?: string | null
  meetLink?: string | null
}>

export type HOST_UPCOMING_BOOKINGS_QUERYResult = Array<{
  _id: string
  guestName?: string
  guestEmail?: string
  startTime?: string
  endTime?: string
  googleEventId?: string | null
  meetLink?: string | null
}>

// Meeting type query results
export type MEETING_TYPES_BY_HOST_QUERYResult = Array<{
  _id: string
  name?: string
  slug?: string
  duration?: 15 | 30 | 45 | 60 | 90
  description?: string | null
  isDefault?: boolean
}>

// User query results
export type USER_WITH_TOKENS_QUERYResult = {
  _id: string
  connectedAccounts?: Array<{
    _key: string
    accountId?: string
    email?: string
    accessToken?: string | null
    refreshToken?: string | null
    expiryDate?: number | null
    isDefault?: boolean
  }>
} | null

export type HOST_BY_SLUG_WITH_TOKENS_QUERYResult = {
  _id: string
  name?: string
  email?: string
  slug?: {
    current?: string
  }
  availability?: Array<{
    _key: string
    startDateTime?: string
    endDateTime?: string
  }>
  connectedAccounts?: Array<{
    _key: string
    accountId?: string
    email?: string
    accessToken?: string | null
    refreshToken?: string | null
    expiryDate?: number | null
    isDefault?: boolean
  }>
} | null

export type USER_CONNECTED_ACCOUNTS_DISPLAY_QUERYResult = {
  connectedAccounts?: Array<{
    _key: string
    accountId?: string
    email?: string
    isDefault?: boolean
  }>
} | null
